- CNC.py
- bCNC.py
Hi,
this pull request fixes two issues:
1. While auto-leveling, the current code ignores non-movement lines, e.g. F200, M3/M5, etc. This fixes it.
2. The default bCNC.ini, which is used in new installations, does not contain a 'probe' option in the 'File' section which raises an exception in profile file saving/loading. This is also fixed by catching the exception and using a default value in this case. Although bCNC.ini should be updated also to contain this File->probe option so no exception is raised in new installations :)
Thanks for this great tool :)
:+1:
> Auto-leveling and probe file load/saving fixes

- bCNC.py
in case of enabling "Check GCode".
The status "check" is always visible in the status display.
> Remove unnecessary open of tab Terminal

- CNC.py
Probing would go from x-begin to x-end, change row, move back to x-begin and start again for the next row.
With this change, when it reaches x-end, changes row and starts probing backwards in the other direction.
Less travel moves, better for us with slower CNCs :).
> Changed probing pattern so it doesn't travel to starting X pos for each row

- bCNC.py
Sometimes I have trouble connecting to the serial port.
The only way I 've found to make this work again is to open the arduino ide serial monitor. This somehow resets correctly the port and I 'm then able to connect again with bCNC.
After some source digging and googling, I made this port opening a little more robust. It 's been working fine for me now for more than a month so I don't think any of the extra commands have any side effects.
> Serial port opening a little more robust

- Pendant.py
With the pendant started, type this address in a browser: http://localhost:8080/icon?name=start32
It will return an empty page.
With this commit, it will return the named icon (start32), as expected :)
> fixed typo for /icon path in pendant

- plugins/midi2cnc.py
The 'rests' were being generated as
```
G04 P0\n
```
(delay always 0)  
Now they are properly generated  
BTW awesome idea @Effer, thanks!! :-D
> Fixed 'rest' delays

- Pendant.py
I have a webcam setup that takes snapshots. I integrated it into the pendant html, but by default baseHTTP in Python returns the jpg with a text/html.
Corrected this based on file extension jpg (and added gif while I was at it, could possibly do more types like png etc.)
> Add mime-type to pendant for jpg and gif

- .gitignore
Small nicety, so people debugging with PyCharm don't have to keep manually excluding the metadata directory from git. ;)
> Add PyCharm's metadata directory to .gitignore

- lib/tkExtra.py
At least in windows OS the input field was not visible. With this is still visible a small flicker when click on the the field. Better than nothing.. any improvement is welcome.
> Text input field in plugin tools was not packed correctly.

- CNCCanvas.py
- ControlPage.py
- bCNC.ini
- bCNC.py
Sometimes it is helpful to be able to align the machine to an existing distinct point or egde and then update the WPOS according to this known position. This adds an action which lets the user click on a known point to update the WPOS.
It also adds key bindings to "1", "2" and "3" to set three pre defined common step widths (0.1 1 10 by default).
> Adds a "Set WPOS" action to the canvas and keyboard shortcuts for jogging

- lib/ttf.py
Still incomplete the matrix transformation for scale and dest/source translation.
Tested working with è and é glyph.
Beware: text field component plugins can't save non ascii data.
> ttf.py complex glyph

- ToolsPage.py
- bCNC.py
To avoid always the mismatch between bCNC.ini file and user .bCNC file when asking for the configuration file.
It's just a draft. I've tested only in windows with a machine with already associated .bCNC files.
> Proposal to open the user's configuration file.

- CNC.py
- ToolsPage.py
As discussed on #200 adding a way to cut from top as option.
or 
Still missing the grouping of added layer as request from @atrueresistance
> Cut from top?

- locale/fr/LC_MESSAGES/bCNC.po
The "È" char doesn't seems to be part of unicode.
> Update bCNC.po, see https://github.com/vlachoudis/bCNC/issues/153

- bCNC.py
At least in windows, if you let camera turned on in canvas, bcnc doesn't close nicely. The GUI close but the python prompt stay there forever.
@vlachoudis there could be better way to handle this. This is just for reference.
> Camera in canvas prevent program to be closed

- Sender.py
I've added the bug, now it should be fixed.
It happened when setting overrride before streaming anything, so it try to send a zero speed feed. That's no good.
> Fix in sending overrided zero feed

- CNC.py
- ControlPage.py
- ToolsPage.py
As point out by @tklus in #345 it wolud be nice to customize the padding of the DRO.  
Like here I believe: 
The settings will be set here (Tools->Machine->DRO Zero padding): 
Then restart bCNC to take effect.
> DRO zero padding

- ControlPage.py
- lib/tkExtra.py
Dirty attempt to allow user input some calculation in the WPOS input fields.
Looking at the code I've notice that the **setY** method in ControlPage.py was wrong (maybe some test left behind?)
Also, during the input the **HOME** key is not disabled. Probably  this should be avoid or it'll start the Home procedure instead of changing the caret position.
> Input Wpos from Float Entry

- lib/tkExtra.py
In windows the self.toplevel.update_idletasks()  is needed. Otherwise the edit field is not visibile, even if it records any keystroke.
It was already committed here https://github.com/vlachoudis/bCNC/commit/9c0c5020e5ce6d53e6f3ee5dda48c4981a6b5723
Is there any problem with this in Linux?
> Fix again InPlaceText in windows

- Sender.py
Don't know how, but the new feed was calculated only  when a new feed was parsed, and not when it was sended. Now it should wok again and fix #409
> Fix override, recalc newFeed on override change

- CNC.py
- Sender.py
- bCNC.py
Save as txt:
- Without bCNC metadata
- Enabled blocks only
- Commands line only
- Uppercase
Should we add a new Save Dialog as proposed by @onekk ?
> Master vasilis save as

- Sender.py
Instead of having the user clear the connected message it is now done automatically when a valid operation is sent to grbl, ie jogging the machine, selecting run/start.
This also corrects problems with run/idle not displaying when connected is displayed.  If the user doesn't clear the connected status message, or select stop or hard reset, then it always stays displayed.  
This also fixes a bug with pause/resume when connected message is displayed - pause would work the first time selected but selecting pause button to do a resume would not work.  Very annoying when using the pendant feature on a tablet since you have to type in resume as a command the first time.
> Automatically clear connected message.

- bCNC.py
- The bug only occured with grbl 1.1 since it now reports **Hold:0** or **Hold:1** instead of **Hold** as in older grbl versions. The fix does not effect operation with grbl 0.9.
> Bugfix: pause button would not resume if job paused (grbl 1.1)

- CNC.py
You may be interested by this fix, which is aimed at a better cooperation with Smoothieware.
I think it should not impact other firmware.
The mesh leveling froze on the first probe (already in contact), but it works with an additional %wait.
Also, smoothie use the last feed ratio for its G0 moves (which is wrong). This makes the leveling extremely slow after the first probe (because probing redefines the F to a very low value). So I just added an explicit single-line F command to reset the "feed" value to the initial value before calling G0. I think it should have no effect on firmwares that handle G0 properly (at maximum machine speed, whatever current feed rate).
> Fixed autoleveling for smoothieware (both freezes and G0 speeds)

- CNC.py
- ProbePage.py
- bCNC.ini
Currently, the probe feed rate is used for tool changes, calibration, and autolevelling.  When autolevelling, it is useful to go slowly so that the tool doesn't damage the PCB surface.  But for tool change and calibration, the sensor is spring loaded and it's possible to move the tool toward the sensor much faster.
However, moving the tool too fast results in inaccurate results.  So instead, start with a fast probe, then back off and try again 10 times slower, over and over, until doing the slowest setting.  This allows for faster probing without sacrificing accuracy.
If the fast feed is unset or is less than or equal to the regular feed speed then this option will have no effect on operation.
> Add fastfeed option for faster calibration and tool changes.

- CNC.py
This fix sets the current gantry work position as initial position instead of (0,0,0)
See issue #603
> Fix autolevel first move issue (#603)

- Camera.py
Rotation first, then translation.
This is much easier to set up.
> Fixed transformation order for camera rotation

- Sender.py
Any "Garbage" data was causing bcnc to throw an error and go into a zombie state. The "Garbage Received" string formatting clauses need a % between the strings and the values.
> Fix broken "Garbage Receive" statements missing a %

- Camera.py
This adds functionality allowing users to customize the capture settings of their attached webcam by setting specific INI properties.
I added this functionality because the camera I use for CNC alignment captures at a high-enough resolution by default that bCNC became unnecessarily slow.  What this feature provided for me was the ability to override the default capture resolution to set it at a more reasonable value.
Note that I've tested only the `height` and `width` properties specifically, and not all cameras support all provided properties.  The other properties are provided because the settings were in nearby documentation and adding the extra options was minimal effort. 
Cheers!
> Add functionality allowing one to specify camera settings via one's INI settings.

- ToolsPage.py
For the translation, String Concatenation is used to reduce the amount of translation.
A newly generated pot.-file will look like this for the translators:
#: ToolsPage.py:481 ToolsPage.py:493 ToolsPage.py:505
msgid "F1"
msgstr ""
#: ToolsPage.py:482 ToolsPage.py:494 ToolsPage.py:506
msgid "F2"
msgstr ""
#: ToolsPage.py:483 ToolsPage.py:495 ToolsPage.py:507
msgid "F3"
msgstr ""
#: ToolsPage.py:484 ToolsPage.py:496 ToolsPage.py:508
msgid "F4"
msgstr ""
#: ToolsPage.py:485 ToolsPage.py:497 ToolsPage.py:509
msgid "F5"
msgstr ""
#: ToolsPage.py:486 ToolsPage.py:498 ToolsPage.py:510
msgid "F6"
msgstr ""
#: ToolsPage.py:487 ToolsPage.py:499 ToolsPage.py:511
msgid "F7"
msgstr ""
#: ToolsPage.py:488 ToolsPage.py:500 ToolsPage.py:512
msgid "F8"
msgstr ""
#: ToolsPage.py:489 ToolsPage.py:501 …
> Shortcuts translatable

- CNC.py
- ProbePage.py
I made wrong assumption about the "mz". I thought it is evaluated after the previous command but in fact it is evaluated as soon as it is fed into the command queue and thus, leading to wrong calculations.
The "%wait" now ensures that the movement has finished before evaluating mz.
Now all my probing scenarios work correctly.
> added "%wait" commands to obtain the correct mz during probing

- CNCRibbon.py
- ControlPage.py
- FilePage.py
- ProbePage.py
- CNCRibbon.py: class PageLabelFrame
- CNCRibbon.py: class PageExLabelFrame
- Filepage.py: class SerialFrame
- ControlPage.py: class ControlFrame
- ControlPage.py: class StateFrame
Tested with a newly generated local pot file on my machine and it works fine
> Translatable labelframe + added missing translating fields

- plugins/driller.py
If you export from KiCad like this (Decimal format)
The codes will be like this 
```
X-44.Y-71.
X-44.Y-93.5
X-38.7Y-13.725
```
We spent much time to figure out what's wrong with all tools from Google and why did not they eat this correctly. Reading this plugin's source code made me realize how bad are things with the Excellon parsers
> [WIP] Supported KiCad Excellon DRL format

- bCNC/controllers/GRBL0.py
- bCNC/controllers/GRBL1.py
- bCNC/controllers/SMOOTHIE.py
Hi!
This is a simple fix that solves sender freezes in situations when G38.2 or similar commands followed by %wait result in grbl Alarm state. In such cases bCNC keeps sio_wait==True until hard reset clears that flag. Soft reset does not help if grbl is configured to use homing cycle because it remains in Alarm state after soft reset and sio_wait remains true.
This definitely works with GRBL1 but I am not so sure about GRBL0 or smoothie.
> Recover from stuck sio_wait in Alarm and Error states

- bCNC/lib/bFileDialog.py
Opening a file using only a keyboard is a bit cumbersome because you need to shift-tab to a file list to navigate through files and folders.
Setting initial focus to file name may be useful in save dialog (but still questionable IMO) but is absolutely useless in open dialog. Will you ever type a filename that you want to open (without autocomplete) instead of just selecting it with arrow keys?
> Move initial focus from file name to file list in open/save dialog

- bCNC/__main__.py
- bCNC/controllers/GRBL1.py
It's a small patch that fixes a couple of issues with pressing HW "Start" button with no g-code lines present in editor.
First - it prevents a crash in `event_generate -> tkMessageBox.showError` call chain from the Sender thread. As stated here: https://bytes.com/topic/python/answers/512683-problems-tkinter-threads and (not so clearly) in docs: https://www.tcl.tk/man/tcl/TkCmd/event.htm#M7 events are dispatched immediately and on the calling thread when invoked without 'when' parameter. Adding `when = 'tail'` moves event processing to the main thread and `showError` no longer crashes the app.
Second - it removes "Running" state that is set a few lines before the "editor empty" check is made.
> Fix crash on hw "Run" button press with no gcode in editor

- bCNC/Pendant.py
This PR is to update de pendant request to add content-size in header to optimize http request and add override data.
This will be helpfull in IOT (arduino / stm32 / etc) project to reduce to get the data : when there is no size content, the iot frameworks wait 1s before get the data.
I update Pendant tools to build a bCNC panel (hardware).
> Add content length on pendant request + Override Data

- bCNC/CNC.py
- bCNC/CNCCanvas.py
- bCNC/Sender.py
Fixes #1375
This change:
Improved scriptability #1256
https://github.com/vlachoudis/bCNC/commit/4456ad2abe63121899e4833f0b3b04323d6e278c
Added the ability for scripting to access 'app', however it only added this for the commandline.
The pull request adds the functionality in two other places.
- sender.py:200           - commandline
- CNCCanvas.py:1817 - opening gcode and rendering
- sener.py:710             - running
> Scripting now always has access to app

- bCNC/plugins/halftone.py
Patch to halftone plugin adds conditional to skip motion commands for spots below min size when the conical mill option is selected. Behaviour mirrors the main "circle" code conditional and results in significant reduction in output for sparse images.
> Reduce halftone plugin output steps with conical mill 

- bCNC/controllers/GRBL1.py
This get rids of the index errors in GRBL1.py when a machine has 4 or 5 axes. It introduces no new functionality otherwise and should be a save patch to apply.
> Quick changes to make GRBL1.py not crash on machines with 4 or 5 axes.

- bCNC/plugins/spirograph.py
> import gcd from math as a fallback

- setup.py
Supporting both python 2.7 and version 3 is hard when the opencv module dropped python 2 support.
Commits like:
https://github.com/lgv2018/bCNC/commit/fef44488ffb7dae469f5891a1b22f002d010a40b trying to fix #1468 
fixed python 2 support, but broke python 3 support as mentioned in #1417 .
Some (LTS) distro's still defaults to python 2. @Harvie wanted to keep support for python 2.
To keep supporting both python versions conditional formatting is needed.
Python 2.7 will be pointed to the last supported openCV version. (4.2.0.32)
Python 3 will be pointed to install the recent opencv version.
Implements some of the code as discussed in  pull request https://github.com/vlachoudis/bCNC/pull/1454
thanks to @GitHubCaps
> Fix opencv-python version, with conditional formatting to point python 2.7 to the last supported version

- bCNC/ToolsPage.py
Option $0 (step pulse time) has been changed from int to float in grblHAL in
https://github.com/terjeio/grblHAL/commit/9845e693296553caff13fcaf5c6a6aff3743152d
Fixes #1463
> parse GRBL config option $0 as float

- bCNC/plugins/pocketwithislands.py
Hi Tomas, 
I think I have found why the reason why last pass was sometimes uneven.
What I am doing is 
- detect we are in the last pass
- if yes, instead of applying standard offset, apply min(diam*stepover/2, diam*0.49)
This should solve the problem detected in #1545
> Uneven lines this is a fix for issue found bye @Harvie in #1545

- bCNC/plugins/dragknife.py
The dragknife plugin currently produces arcs that fail validation when
sent to grbl.
When the tangentialOffset method is called on an arc segment, both it's
start and end position are offset. The center is moved such that it is
equidistant between these new positions. This produces a valid arc.
However, when turned into GCode, only the center and end positions are
used - the start position is assumed to be the end position of the
previous command. This _isn't_ a valid arc, and GCode processors like
grbl will report errors when sent this GCode.
This commit fixes the problem by using the end of the previous (tangentially
offset) segment as the start of subsequent offset arc segments.
> Fix bug in dragknife plugin

- bCNC/bCNC.desktop
The `Keywords` entry is recommended to be present in `*.desktop` files. We can add a few keywords as a first start.
> bCNC.desktop: add Keyword key

- bCNC/Sender.py
- bCNC/lib/bFileDialog.py
- bCNC/lib/dxf.py
- bCNC/lib/imageToGcode.py
- bCNC/lib/spline.py
Some shebangs are used in files which are not executable. Thus they are not useful and should be removed.
> remove unused shebangs

- bCNC/bmain.py
Previous codefactor push changed the text formatting of the buffer bar status text to a floating point number.  Added formatting to force number to be displayed as a integer whole number.
Changes to be committed:
modified:   bCNC/bmain.py
> [FIX] reset buffer bar text formatting

- setup.py
This is due to https://peps.python.org/pep-0420/
Reported in:
https://bugzilla.redhat.com/show_bug.cgi?id=1684603#c17
Signed-off-by: Jaroslav Škarvada <jskarvad@redhat.com>
> Fixed "Package would be ignored" warning

- bCNC/controllers/_GenericController.py
Hitting the Stop button resets the TLO value field shows zero, however the actual TLO value sets correctly set to it's previous value. Calling self.viewParameters() updates the TLO field correctly.
> Update TLO after Stop button is hit

- bCNC/plugins/text.py
- setup.py
This is a fix for #1811 
Tested with ttf fonts for no regression tests
Tested with shx fonts, using both arcs and lines.
> Shx fonts support in text plugin

- bCNC/lib/dxf.py
According to [DXF Reference](https://help.autodesk.com/view/OARX/2023/ENU/?guid=GUID-7D07C886-FD1D-4A0C-A7AB-B4D21F18E484), entities have **group codes** (which are named **tags** in bCNC). Some of the group codes, on some entities, represent list values. For example the doc for [LWPOLYLINE entity](https://help.autodesk.com/view/OARX/2023/ENU/?guid=GUID-748FC305-F3F2-4F74-825A-61F04D757A50) on group code 10 says "Vertex coordinates (in OCS), multiple entries; one entry for each vertex".
Current implementation in bCNC is lazy, it doesn't know if the value should be a list or not :
- the first time a tag is encountered, bCNC stores the value as a scalar
- the second time this tag is encountered, bCNC replaces the existing scalar with a list of [existing, new] values
- then if the tag is …
> Fix edge case in DXF import, closes #1499

- flatpak/README.md
Fixes errors in the flatpak README.md:
- fix --device argument: $ flatpak run --device=/dev/ttyUSB1 --share="$HOME" io.github.bcnc error: Unknown device type /dev/ttyUSB1, valid types are: dri, all, kvm, shm
- remove --share option $ flatpak run --device=/dev/ttyUSB1 --share="$HOME" io.github.bcnc $ error: Unknown device type /dev/ttyUSB1, valid types are: dri, all, kvm, shm
Tested on Fedora 38 using flatpak:
$ flatpak --version
Flatpak 1.15.4
> Fix/improve flatpak README

- flatpak/io.github.bcnc.json
Fixes the following flatpak build error:
clinic/_tkinter.c.h:544:20: error: initializer element is not constant
544 |     {"dooneevent", _PyCFunction_CAST(_tkinter_tkapp_dooneevent), \
METH_FASTCALL, _tkinter_tkapp_dooneevent__doc__},
by sticking to the last working version.
The very latest revision is an adjustment for python 3.11 and does not compile with python 3.10.
> Stick to working version of tkinter-standalone

- bCNC/VScrollFrame.py
- bCNC/bmain.py
Vertical scrollbar for left side of the screen. Allows to use smalls screens like 1024x600 (Raspberry Pi)
> Vertical scrollbar to make small screens easier to use

- bCNC/Utils.py
Fixes:
Utils.py:213:9: F841 local variable 'errorReport'
is assigned to but never used.
> Fix unused errorReport variable

- bCNC/plugins/spirograph.py
Just notice the plugin was broken, probably due to changes in python
> Fix Spirograph not working, gcd require int

- bCNC/Camera.py
- bCNC/Pendant.py
Both OpenCV (for the camera) as well as PIL.Image (for the Canvas) can work with buffer like objects, which then can be immediately written out by the webserver code.
> Get rid of temporary files for web pendant

- flatpak/io.github.bcnc.json
Update due to flatpack's complaints:
Info: org.freedesktop.Platform is end-of-life,
with reason: org.freedesktop.Platform 22.08 is no longer
receiving fixes and security updates.
Please update to a supported runtime version.
> Update org.freedesktop.Platform to 24.08

- bCNC/Sender.py
- bCNC/ToolsPage.py
This should be a fix for #1910.  Tested on both 3.13 and 3.12 on Debian Bookworm
> Fix dynamic loading of controllers and plugins in Python 3.13

- setup.py
python-opencv 4.5.5.62 has been yanked and is no longer available: https://pypi.org/project/opencv-python/4.5.5.62/
4.5.5.64 is the next version up that is still available, but not the newest version. Maybe there is interest in generally updating; the current version of python-opencv is 4.1.0.68. 
However I don't understand the implications of updating, so I stuck with recommended version.
> Update python-opencv version

- bCNC/controllers/GRBL1.py
This fixes a problem i had in `toolChange`, where `%wait` continues too soon after a command which transitions through an idle state, which isn't recognised if it's sent as `Hold:0` or `Hold:1`.
As per my other PR, this caused an issue with uCNC, and might not with other controllers, though GRBL does apparently send `Hold:0` and `Hold:1`.
> GRBL1: account for Hold sub-states in wait condition

- bCNC/CNCCanvas.py
Comparison was with None, but tk.NONE is used for this variable, which are different.
This broke the "gantry" camera mode for me; with this change it works as expected.
> use correct NONE to compare cameraAnchor

- bCNC/plugins/driller.py
https://github.com/vlachoudis/bCNC/commit/5fdfd235322a145de7cc26bab986b92fcd1e756e claims to add support for a feature from Eagle's Excellon drill file format, which is the specification of the number of decimals for coordinates as an operand to the `METRIC` or `INCH` commands.
https://github.com/vlachoudis/bCNC/blob/5aab96b12f9f96794abfc47af661ba5fc7767d4b/bCNC/plugins/driller.py#L111-L116
Unfortunately, if this precision isn't specified, the `line.index()` call raises an error and the plugin crashes.
KiCad doesn't add precision information after `METRIC` and `INCH` commands in its drill files, so the Driller plugin crashes when importing those files.
This pull request allows for the plugin to not crash and instead process a KiCad drill file normally, assuming that the coordinates in the …
> Fix import of KiCad drill files in Driller plugin
