- CNC.py
- bCNC.py
> Fix roundFunc

- bCNC.py
This would be a way to give more information about Pendant to a user who test for the first time.
> Add more verbose dialog to pendant start command.

- bCNC.py
Feed Override Test, 
I've made some test to implements an usefull function for override feed during line feed to grbl.
I know that this approach is far from optimized, but this feature is realy a must for test materials with cnc.
I hope that grbl 1.0 will finaly implements feed overrrides.
> Feed Override

- bCNC.bat
For the "poor" windows user ;)
> Fix python path for plugin directory on windows os

- Pendant.py
- bCNC.py
- pendant/index.html
I find this a missing feature in the pendant interface, an idea for an easy way to upload file from another  terminal.
I suggested it a while ago, but at that time it seemed that the web interface was completely rewritten. Now some time had passed and maybe it can find a place in this eval branch.
It's still quite raw and untested, comments,suggestions (or rejections) are welcome.
> Pendant upload file

- plugins/spirograph.py
because also points are important...
> Fix init values in Spirograph

- plugins/bowl.py
Let me know if this is the correct approach for error handling
> Included stepover in bowl calculations

- ToolsPage.py
Does it need the conversion? Or have I misunderstood?
> End Mill Stepover percentage as a pure number.

- plugins/flatten.py
- plugins/pyrograph.py
added checks on user parameters,
give feedback in case of wrong settings.
> Flatten tool fix: checked user parameters.

- CNC.py
- Sender.py
- bCNC.py
- lib/stl.py
This time not a plugin ;)
It's more a integration on what already exist for probed data.
Probing with high details take a lot of time, but result are nice.
Here the original:
And here the exported result as STL file:
I've chose stl because seems really appreciated by 3d makers.
> Save probe data as STL file.

- Ribbon.py
Really LightYellow and White was not clearly visible..
> Improve contrast on the usefull recent menu

- bCNC.py
Hi @vlachoudis isnt' this to be consider as pure number and so not to be converted from mm/inch?
> Step over as pure number?

- lib/bFileDialog.py
Filetype was not the same for upper and lower case
> Improve open file color also for image type

- plugins/pyrograph.py
> Adjust pyrograph border and give more feedback on ouput size

- pendant/index.html
I have added buttons to the pendant web page for zeroing the x,y, and z axis individualy.  It does make the button layout a little more busy but I find it very handy when using my tablet as a pendant for my machine.  A lot of times I am having to zero a single axis when setting things up and find it easier tapping the tablet screen than trying to type in the G command.
> - added buttons to pendant for zeroing x,y,z axis individualy

- plugins/bowl.py
- plugins/box.py
- plugins/driller.py
- plugins/flatten.py
- plugins/gear.py
- plugins/heightmap.py
- plugins/midi2cnc.py
- plugins/pyrograph.py
- plugins/spirograph.py
- plugins/text.py
- plugins/tile.py
Have to explicitly set \__doc__ when doing text translation for plugin docstring that are being used for tooltip.
This fixes issue #180.
> - Bugfix: plugins not displaying proper tooltip

- CNCCanvas.py
It seems that tab addition introduce this issue.
> Fix issue when moving object

- bCNC.py
To allow to load a file and run from command line
es:
python bCNC.py --run c:\test.ngc
> run option

- Ribbon.py
I found it useful to have "at hand" when testing.
What do you think?
> "New File" always accessible from basic buttons

- Updates.py
- bCNC.py
> Removed unused method and reference to Fluka.

- bCNC.py
I found annoying when close by mistake.
The same option should be added even if the save dialog of the file IMO.
> Allow user to cancel while exiting with modified gCode.

- plugins/driller.py
* drill even not enable block
* avoid error on void bids
> driller fix

- Sender.py
- bCNC.py
- lib/tkExtra.py
Hi,
this is just a propose to have some sort of indicator of the grbl buffer state. Here it's the green pie graph on the bottom right:
I know is not really nice but with big files the green and orange bar quite overlaps and I'm often in doubt if I'm streaming too slow to the controller. 
Any improvement is welcome.
> Buffer fill indicator

- locale/fr/LC_MESSAGES/bCNC.po
> Revert "Update bCNC.po, see https://github.com/vlachoudis/bCNC/issues/153"

- bCNC.py
- lib/tkExtra.py
> minor adjust to buffer meter

- lib/tkExtra.py
> Text input field missing in window os

- CNCCanvas.py
- bCNC.ini
As suggest in #291 by @sgtbidu , added a user selectable color for probe text data
> Master probe text color

- CNC.py
- CNCCanvas.py
Allow custom color to block of gcode. Still missing the GUI side to adjust it.
> Add custom color to block of gCode

- plugins/heightmap.py
The missing option to finish a job with a single pass.
> Heightmap plugin: Single pass for finish

- ProbePage.py
Just a minor correction to tool tip for Camera freeze.
> Tool tip correction for camera freeze image

- CNC.py
- CNCList.py
- EditorPage.py
- Ribbon.py
- bCNC.py
I hope to have kept a coherent style with the rest of the code. Encountered some difficulties on understand the editor stuff.
I was thinking that the only context menu now present in bCNC is the one on the state machine button. Wouldn't be a nice GUI improvement to have all the editor Ribbon Menu show as a Context Menu when Right Click in the canvas?
> Change block of colors

- CNC.py
> Copy Color

- bCNC.py
To fix #315 buffer fill now use a well tested component.
> Buffer Bar

- Sender.py
Try to fix problem with feed override #341 
It could still exist a special case, not covered by this fix
> Sender-Override-Fix

- ControlPage.py
Avoid rounding when zero digits padding
> Fix zero digit padding

- bCNC.py
I'm always in doubt if the file has been automatically reloaded by bCNC when modified externally.
This is a propose to make it more verbose, please fix style and any function sign if you don't like it.
(and let me know for the next time :)
> Master vasilis auto load

- lib/bFileDialog.py
If anybody could test in linux.
It's a sort of trick, but does its job.
> Fix for #433 at least in windows

- plugins/flatten.py
> Remove some unused reference in flatten plugin

- CNCCanvas.py
- bCNC.ini
Usefull for #490 and balck themed desktop.
> Change canvas back color as option

- CNC.py
- ToolsPage.py
- Utils.py
- bCNC.ini
Allow user to get monstrous icons on their High Resolution Display.
> Double size icon in user settings

- Sender.py
Attempt to implement issue #663 
Tested on smoothie and seems to work.
> Modify status handling for new smoothie query format

- plugins/driller.py
Better compatibility with laser mode
> driller laser mode compatible

- Pendant.py
- pendant/index.html
Hey there @vlachoudis -- I hacked together this little bit of functionality just to scratch my own itch, and am submitting this PR just in case you might find such functionality useful.
I'm not totally sure I'm on-board with merging this as-is -- it's a little bit of a hack, honestly, but I did briefly consider adding configuration options allowing this (and a couple other existing features) to be configured from the `ini` file.  In the end, I decided to table the idea of adding the configuration options because I thought it might be better to consider swapping out some parts of the hand-brewed web server with something providing a little more out-of-the-box functionality.  I'd be glad to chat with you about what I can help you with if you were on-board with such an idea.
Cheers! …
> Adds functionality showing the displayed CNCCanvas in Pendant.

- ControlPage.py
Add coolant control to the 'Control Panel'
Uses G-Codes M7, M8 and M9
> add coolant control

- ControlPage.py
> added missing translateing fields

- Utils.py
german translation - behind @feistus
> added @SteveMoto [about]

- plugins/driller.py
Hallo,
I insert a option to use only the anchor points for drillholes.
Second I use the name for the name in the editor.
> Driller use anchor and name in Editor

- CNCList.py
- EditorPage.py
- bCNC.py
Comment and uncomment selected rows in editor by click the button
> comment uncomment rows added

- plugins/driller.py
If the path closed (last point == first point) or a point is multiple times in the process list, it will be remove from list.
> Driller closed path

- plugins/driller.py
See https://github.com/vlachoudis/bCNC/issues/809
> Excellon drill file import

- bCNC.pot
state: POT-Creation-Date: 2018-06-17 23:44+0200
> Update bCNC.pot [root]

- bCNC/CNC.py
> add 5s pause after tool change

- bCNC/plugins/text.py
Text prepared to be separated into blocks.
Only "cut here" was added at the end of each contour.
Executing Split divides the text one block per in each closed contour. Execute Join joins in a single block.
> Update text.py - Preparated to be separated into blocks

- bCNC/lib/imageToGcode.py
Signed-off-by: Jaroslav Škarvada <jskarvad@redhat.com>
> Fixed GPL snail mail address

- bCNC/plugins/trochoidal.py
- Lead into and out of trochoidal path segment using small half circle for smooth motion
- Removed several unneeded linear moves which caused even backward motion because of rounding issues
- split circles into half circles, otherwise GBRL controller seems to have problems sometimes
- Comments added, some restructuring to improve readability
Issues were observed while milling an e-guitar body contour consisting of lines and arc segments,
fixes above solved them.
All in all a very usable great tool, thanks! :-)
Rgds, Juergen
> Several fixes for Trochoidal Tool

- bCNC/ControlPage.py
- bCNC/EditorPage.py
- bCNC/FilePage.py
- bCNC/ProbePage.py
- bCNC/TerminalPage.py
- bCNC/ToolsPage.py
- bCNC/Updates.py
- bCNC/Utils.py
- bCNC/__main__.py
- bCNC/bCNC.ini
- bCNC/lib/bFileDialog.py
- bCNC/lib/tkDialogs.py
- bCNC/lib/tkExtra.py
System colors customization (very useful for dark Ubuntu system themes).
> System colors customization

- bCNC/plugins/driller.py
Should work well for using laser with M3 constant power.
> driller.py fix issues #1300 #1301

- setup.py
This allows development inside an IDE like IntelliJ Idea on Mac.
> Add requirements for Mac

- bCNC/FilePage.py
- bCNC/ToolsPage.py
- bCNC/Utils.py
> import sys

- bCNC/plugins/pocketwithislands.py
Hi @Harvie , I have added the G1 moves to link the pocket paths instead of useless G0 outside of the material
I just added the new segments to the full path, and then reordered all this with split2contour.
It is not optimal in terms of procesing time, we could optimize later to have the path directly ordered, but we have to admit than we can wait some processing seconds when doing a pocket, most of the time is spent on machining the piece of metal on the CNC ;-)
It works fine for me in most cases that I have tested. However, I have found one case where I get strange moves inside the profile, with strange g2 moves that I cannot understand at the moment.
But seems to work fine in most cases
Have a good day
Pierre
> linking pocket paths with g1 moves; split2contours did the job for me ;)

- bCNC/plugins/pocketwithislands.py
Hi @Harvie 
As discussed in #1534
> I have found one case where I get strange moves inside the profile, with strange g2 moves that I cannot understand at the moment.
This comes from weird side effects in split2contours
To allow user to generate a pocket in these rare cases, _**I have added the option of disabling G1 segments**_ linking pocket paths.
This is more flexible, and allows the user finding an alternative solution if this occurs, until we have fully understood the problem in split2contours, but I would not like to touch this function at the moment.
All the best
Pierre
> allow disable g1 moves inside pockets (to cover strange side effects of split2contour)

- bCNC/plugins/pocketwithislands.py
Just a fix for Island offset, as discussed in #1536
> fix offsetIsland Interesect and exclude

- bCNC/plugins/pocketwithislands.py
try to merge profile, pocket, pocket with islands into a single experimental plugin
> Pocket islands plugin

- bCNC/lib/bpath.py
- bCNC/plugins/pocketwithislands.py
Add overcuts and additional cuts inside corners
> overcuts and additional cuts

- bCNC/CNC.py
- bCNC/plugins/pocketwithislands.py
Hi
- I have added ignore islands option => choice among the following list :
Regard all islands except tabs,
Ignore all islands,
Regard only selected islands
- I have added some help inside the plugin
> add ignore islands option  / add some doc help

- bCNC/plugins/pocketwithislands.py
After furhter tests, I have found that these changes increase stability of the plugin pocketswithislands.
Pierre
> Increase Stability of Pocket with Islands Plugin

- bCNC.1
A man mage is always nice to have to understand what a program is and how it can be invoked. It is a start that can then be improved to add more details if needed.
> introduce bCNC.1 man page

- bCNC/plugins/driller.py
The plugin behaved very strangely when importing .xln files generated from Autodesk Eagle.
The number of decimal places is now read from the beggining of the file instead of the number of digits, which isn't constant with Eagle.
Also added a tool change command if the machine isn't a laser cutter.
> Modify driller plugin to work with Eagle's Exellon

- bCNC/lib/stl/base.py
Fixes https://github.com/vlachoudis/bCNC/issues/1663
> Import ABC from collections.abc for Python 3.10 compatibility.

- bCNC/plugins/trochoidPath.py
fixes #1742 
@vlachoudis @Harvie 
Please prioratize this one.
> [FIX] Indentation Error

- bCNC/controllers/_GenericGRBL.py
- bCNC/plugins/endmilloffset.py
> Fix follow-up typos

- bCNC/bmain.py
Not sure how this happened was fine locally
> fix push reloacted parentheses

- bCNC/ControlPage.py
- bCNC/Sender.py
- bCNC/controllers/G2Core.py
- bCNC/controllers/_GenericController.py
Tested against an Arduino Due on a full sheet gantry router.
> Initial support for G2Core

- bCNC/CNC.py
1- Correct profile with pocket activated in multiple selection.
2- Correct stepover parameter for pocket .
3- Add updown field in pocket to allow to be placed in up position
4- The pocket operation is now before the profile operation.
5- On the canvas, the generated profile and pocket operations are selected
> Fixes to Profile when pocket is enabled

- bCNC/Sender.py
INTEGRATED: -  
<issue>#1318</issue>  
<type> BUG FIX </type>  
<audience>Customer</audience>  
<description>connection problem due to serial decode </description>
> bCNC - Sender: update serial decode to ignore unreadable characters

- bCNC/bCNC.desktop
> bCNC.desktop: add Categories

- bCNC/plugins/jigsaw.py
It also reduces the radius of the basic taps, to avoid collisions on very small puzzles
> Jigsaw plugin: Add deviations in the crossings of the cuts, so that every piece can change in size

- .gitignore
- flatpak/README.md
- flatpak/io.github.bcnc.json
This is my first flatpak packet, i test it on fedora-38, not all func, but only week have cnc and use any app for this.
> Add flatpak manifest

- bCNC/locales/ru/LC_MESSAGES/bCNC.po
> Update Russian translation

- bCNC.sh
- bCNC/ProbePage.py
Hello,
This is a new PR as ProbePage.py diverge too much
Please see old PR #1701 for reference.
Regards.
> Added autogoto to saved settings

- bCNC/plugins/box.py
Allows to optionally create boxes without a cover. Meaning that it will skip the zigzag on the top edges of the box, and omit the top side.
> Box cover is optional

- bCNC/lib/meshcut.py
- bCNC/plugins/slicemesh.py
Fixes https://github.com/vlachoudis/bCNC/issues/1888
> Numpy: migrate from removed `int`,`bool` to `int_`, `bool_`.

- bCNC/ControlPage.py
Fix indentation of several lines, in order to remove them from the exception
> Fix Display of abc coordinates

- bCNC/plugins/text.py
I have noticed that when using SHX fonts there's a dot drilled in between every letter. It's not a problem with the font itself, and it happens always. I have modified the code to delegate the `CNC.zenter(depth)` command to where it's actually used (before a `gline`), instead of doing it at the end of every `grapid` movement. This saves lots of time and removes the bug of the extra drill between letters.
> text-plugin: Remove separation marks between characters when processing SHX fonts
